name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch
        run: curl -X POST -u "lime:${{ secrets.PAT_TOKEN }}" -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/groggyegg/lime/dispatches -d '{"event_type":"build"}'
